name: Auto Update RSS Feed

on:
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Update feed.xml
      run: |
        DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        FEED_FILE="feed.xml"
        NEW_ITEM="<item><title>Delhi NCR Summary - $DATE</title><link>https://vinay13893.github.io/delhincr-realty-feed</link><pubDate>$DATE</pubDate><description><![CDATA[<ul><li><strong>Update:</strong> Triggered at $DATE</li></ul>]]></description></item>"

        awk -v item="$NEW_ITEM" '/<\/channel>/ { print item } 1' "$FEED_FILE" > temp.xml && mv temp.xml "$FEED_FILE"

    - name: Commit and Push changes
      run: |
        git add feed.xml
        git commit -m "Auto update RSS feed at $DATE"
        git push origin main
